import api from './api';
export const agencyApi = {
  me: () => api.get('/agency/me').then(r => r.data),
  updateMe: (data: any) => api.put('/agency/me', data).then(r => r.data),
  getProfile: () => api.get('/agency/profile').then(r => r.data),
  updateProfile: (data: any) => api.put('/agency/profile', data).then(r => r.data),
  listSquad: () => api.get('/agency/squad').then(r => r.data as any[]),
  createSquad: (data: any) => api.post('/agency/squad', data).then(r => r.data),
  createSquadInvite: (data: { full_name: string; email: string; role_type: 'member'|'manager' }) => api.post('/agency/squad/invite', data).then(r=>r.data),
  updateSquad: (id: string, data: any) => api.put(`/agency/squad/${id}`, data).then(r => r.data),
  deleteSquad: (id: string) => api.delete(`/agency/squad/${id}`).then(r => r.data),
  listMemberProfiles: () => api.get('/agency/member-profiles').then(r => r.data),
  createMemberProfile: (data: any) => api.post('/agency/member-profiles', data).then(r => r.data),
  updateMemberProfile: (id: string, data: any) => api.put(`/agency/member-profiles/${id}`, data).then(r => r.data),
  deleteMemberProfile: (id: string) => api.delete(`/agency/member-profiles/${id}`).then(r => r.data),
  listGeneral: () => api.get('/agency/general-portfolios').then(r => r.data),
  createGeneral: (data: any) => api.post('/agency/general-portfolios', data).then(r => r.data),
  updateGeneral: (id: string, data: any) => api.put(`/agency/general-portfolios/${id}`, data).then(r => r.data),
  deleteGeneral: (id: string) => api.delete(`/agency/general-portfolios/${id}`).then(r => r.data),
  listPortfolio: (params?: any) => api.get('/agency/portfolio', { params }).then(r => r.data),
  addPortfolio: (data: any) => api.post('/agency/portfolio', data).then(r => r.data),
  deletePortfolio: (id: string) => api.delete(`/agency/portfolio/${id}`).then(r => r.data),
  total: () => api.get('/agency/total-portfolio').then(r => r.data),
  preview: (params?: any) => api.get('/agency/preview', { params }).then(r => r.data),
  publicView: (agencyId: string, params?: any) => api.get(`/agency/public-view/${agencyId}`, { params }).then(r => r.data),
  categories: () => api.get('/public/categories').then(r => r.data),
  subscriptions: (status: string = 'pending') => api.get('/agency/subscriptions', { params: { status } }).then(r => r.data as any[]),
  assignments: (status: string = 'pending') => api.get('/agency/assignments', { params: { status } }).then(r => r.data as any[]),
  unreadCount: () => api.get('/agency/subscriptions/unread-count').then(r => r.data as { count: number }),
  respondCard: (recipientId: string, action: 'accept' | 'reject') => api.patch(`/agency/cards/${recipientId}/respond`, { action }).then(r => r.data),
  getOffer: (recipientId: string) => api.get(`/agency/cards/${recipientId}/offer`).then(r => r.data),
  submitOffer: (recipientId: string, data: any) => api.post(`/agency/cards/${recipientId}/offer`, data).then(r => r.data),
  respondOffer: (recipientId: string, data: any) => api.post(`/agency/cards/${recipientId}/offer/respond`, data).then(r => r.data),
  allOffers: () => api.get('/agency/offers').then(r => r.data as { offers: any[] }),
  backfillCards: () => api.post('/agency/cards/backfill').then(r => r.data as { inserted: number }),
};
