// Industries used by the Industry Experience section of the job-profile builder.
export const INDUSTRY_OPTIONS: string[] = [
  'Information Technology / Software',
  'IT Services & Consulting',
  'SaaS / Cloud',
  'E-commerce',
  'Retail',
  'FMCG',
  'Consumer Durables',
  'Banking & Financial Services',
  'NBFC / Fintech',
  'Insurance',
  'Real Estate',
  'Construction & Infrastructure',
  'Manufacturing',
  'Automobile',
  'Healthcare & Pharma',
  'Hospitals & Diagnostics',
  'Education & EdTech',
  'Telecom',
  'Media & Entertainment',
  'Advertising & Marketing',
  'Travel & Hospitality',
  'Logistics & Supply Chain',
  'Agriculture & Agritech',
  'Energy & Utilities',
  'Textiles & Apparel',
  'Food & Beverage',
  'Chemicals',
  'Electronics & Hardware',
  'Professional Services',
  'Government / PSU',
  'Other',
];
